### ISSUE TITLE
About nli dataset

### ISSUE THREAD

**Issue by Fang-git0** [LZY-the-boys/MIRACLE#2]
--data-path 'dataset/nli.jsonl' --dev-data-path 'dataset/dev_nli.jsonl'  

Hello, I see that the NLI data set is used, and I would like to ask where to download it. The format of the NLI data set I found is different from yours, so I am not clear about the format of your data set.

Thank you very much.

**Comment by Fang-git0** [comment]
“We fine-tune the NLI model using the dataset con-
structed from our data. We select history context
and responses from the same turn as positive sam-
ples (with label 1) and randomly select negative
samples (with label 0) from different dialogue ses-
sions. The NLI model achieves a test accuracy of
93.2%.”

I saw that in the paper. When I tried to use such format "

{"input":  "It's true, being among nature can be grounding. Do you have a favorite plant or flower?","labels": "1", "output": "Ooh, gardens can be so therapeutic. They help people feel calm and at peace."}

however, I got an error, could you please tell me your nli data set format, thank you very much

**Comment by LZY-the-boys** [comment]
Sorry for the confusion, our nli dataset format is 
```
{"input": "User:Hey, how's it going? Have you been keeping up with your exercise routine lately?\n\nAssistant:Yeah, I try to walk every day.\n\nUser:That's great! How far do you usually walk?\n\nAssistant:About three miles.\n\nUser:Three miles every day? That's impressive. How long does it usually take you?\n\nAssistant:", "output": "Not sure, I just walk until I don't want to anymore.", "labels": 1}
{"input": "User:Hey, how's it going? Have you been keeping up with your exercise routine lately?\n\nAssistant:", "output": "I didn't really choose, just grabbed something.", "labels": 0}
```
where labels 1 represents positive pair (consistent), 0 represents for negative pair (inconsistent)

**Comment by Fang-git0** [comment]
Hello. Thank you very much. But using the data in this format, there are still errors when it runs.
May I ask whether this is due to insufficient data, or where the model parameters are not set to cause such problems?

bash train_nli.sh

The error message is as follows: 
2024-03-25 21:13:27,103 | INFO The following columns in the training set don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: output, input. If output, input are not expected by `BertForSequenceClassification.forward`,  you can safely ignore this message.
/data/lilinfang/.conda/envs/miracle/lib/python3.9/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
2024-03-25 21:13:27,116 | INFO ***** Running training *****
2024-03-25 21:13:27,116 | INFO   Num examples = 190
2024-03-25 21:13:27,116 | INFO   Num Epochs = 25
2024-03-25 21:13:27,116 | INFO   Instantaneous batch size per device = 16
2024-03-25 21:13:27,116 | INFO   Total train batch size (w. parallel, distributed & accumulation) = 128
2024-03-25 21:13:27,116 | INFO   Gradient Accumulation steps = 8
2024-03-25 21:13:27,117 | INFO   Total optimization steps = 25
2024-03-25 21:13:27,117 | INFO   Number of trainable parameters = 109,483,778
  0%|                                                                                                                                                        | 0/25 [00:00<?, ?it/s]You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
{'loss': 0.7413, 'learning_rate': 2.5e-05, 'epoch': 0.67}                                                                                                                           
  4%|█████▊        
Traceback (most recent call last):
  File "/data/lilinfang/miracle/train_classify.py", line 467, in <module>
    defopt.run(_start)
  File "/data/lilinfang/.conda/envs/miracle/lib/python3.9/site-packages/defopt.py", line 356, in run
    return call()
  File "/data/lilinfang/miracle/train_classify.py", line 459, in _start
    train_nli_classify(args)
  File "/data/lilinfang/miracle/train_classify.py", line 319, in train_nli_classify
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
  File "/data/lilinfang/.conda/envs/miracle/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/data/lilinfang/.conda/envs/miracle/lib/python3.9/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/data/lilinfang/.conda/envs/miracle/lib/python3.9/site-packages/transformers/trainer.py", line 2205, in _maybe_log_save_evaluate
    logs["loss"] = round(tr_loss_scalar / (self.state.global_step - self._globalstep_last_logged), 4)
ZeroDivisionError: float division by zero
  4%|█████▊

**Comment by LZY-the-boys** [comment]
It seems you have `self.state.global_step` == `self._globalstep_last_logged` according to the error messages you attached . May you try set the `args.resume_from_checkpoint = False`?

**Comment by Fang-git0** [comment]
` # save args

    utils.to_json(args.__dict__, f'{args.output_path}/train_args.json')
    
    args.resume_from_checkpoint = False # 
    
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
    model.save_pretrained(f'{args.output_path}/best')
    if args.use_wandb:
        wandb.config.update(args, allow_val_change=True)
        logger.info({'wandb-url': wandb.run.get_url()})`

Add this line, still have the same error.
